### PR TITLE
...

### PR DESCRIPTION
**Pull request by IzaacCoding36**
please accept this.

### CODE REVIEW

**Comment by IzaacCoding36** [comment]
Co-authored-by: IzaacCoding36 <izaaccoding@gmail.com>
Co-authored-by: CodeRaptor92 <lixoevida3@gmail.com>

**Comment by CodeRaptor92** [comment]
Co-authored-by: IzaacCoding36 izaaccoding@gmail.com
Co-authored-by: CodeRaptor92 lixoevida3@gmail.com

**Comment by IzaacCoding36** [comment]
Co-authored-by: IzaacCoding36 <111022921+IzaacCoding36@users.noreply.github.com>
Co-authored-by: CodeRaptor92 <144403275+CodeRaptor92@users.noreply.github.com>

**Comment by CodeRaptor92** [comment]
cmon :/ i just wanted to code this all by myself

**Comment by CodeRaptor92** [comment]
but if you insist i won't do this anymore :)

**Review by CodeRaptor92 — COMMENTED** [review]
alts added, like always huh <-<

**Pull request merged**
